version: "2"

services:
  app:
    build: ./
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/:delegated
    depends_on:
      - db
  db:
    image: mysql
    env_file: .env
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql:delegated
      - ./src:/var/www/html/:delegated

volumes:
  mysqldata:
